version: "3.9"

volumes:
  spotify_postgres_data:
  kestra_postgres_data:
  kestra_data:

networks:
  data-network:

services:
  # ----------------------------------
  # Spotify Project Database
  # ----------------------------------
  spotify_postgres:
    image: postgres:16
    container_name: spotify_postgres
    environment:
      POSTGRES_USER: spotify_user
      POSTGRES_PASSWORD: spotify_password
      POSTGRES_DB: spotify_analytics
    ports:
      - "5432:5432"
    volumes:
      - spotify_postgres_data:/var/lib/postgresql/data
    networks:
      - data-network

  # ----------------------------------
  # pgAdmin
  # ----------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    depends_on:
      - spotify_postgres
    networks:
      - data-network

  # ----------------------------------
  # Kestra Internal Database
  # ----------------------------------
  kestra_postgres:
    image: postgres:16
    container_name: kestra_postgres
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
    volumes:
      - kestra_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kestra"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data-network

  # ----------------------------------
  # Kestra
  # ----------------------------------
  kestra:
    image: kestra/kestra:v1.1
    container_name: kestra
    command: server standalone
    user: root
    depends_on:
      kestra_postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ~/.config/gcloud:/root/.config/gcloud:ro
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: kestra

        kestra:
          repository:
            type: postgres
          queue:
            type: postgres
          storage:
            type: local
            local:
              basePath: /app/storage
          server:
            basicAuth:
              enabled: true
              username: admin@kestra.io
              password: Admin1234!
          url: http://localhost:8080/
    networks:
      - data-network

  # ----------------------------------
  # Spotify Python Ingestion Container
  # ----------------------------------
  spotify_ingestion:
    image: python:3.12
    container_name: spotify_ingestion
    working_dir: /app
    volumes:
      - ./spotify:/app
    stdin_open: true
    tty: true
    networks:
      - data-network
